### ISSUE TITLE
Error: Could not find ffi-1.9.2 in any of the sources

### ISSUE THREAD

**Issue by malopezcruz** [axyz/middleman-zurb-foundation#2]
In step 3, after the bundle install, I get the following error: "Could not find ffi-1.9.2 in any of the sources". I tried to install the gem with gem install ffi-v 1.9.2, but I get this other message: 

ERROR: Could not find a valid gem 'ffi' (= 1.9.2) in any repository
ERROR: Possible alternatives: ffi. 

I did the latter, but the installed version is 1.9.3.
Any idea how to solve it? Thanks.

**Comment by axyz** [comment]
what SO are you using? for my personal experience on linux i've never had these kind of problem, while on mac i had a similar problem i struggled with a lot. I had the same error, but with the i18n package. I've resolved using rvm to setup a clean ruby environment. Give it a try and let me know if it helped.

**Comment by axyz** [comment]
basically: refer to http://rvm.io in order to setup a clean ruby environment for your architecture, then activate it on your active shell (see the rvm docs for your OS) then only `gem install bundle` and from your project do a `bundle install` it will install all the needed gems. 

N.B. before the bundle install my advice is to erase your old .bundle/config and also the Gemfile.lock

**Comment by malopezcruz** [comment]
Thank you very much for the recommendations. My os is OSX, Maveriks. I'll let you know what the outcome was.

**Comment by axyz** [comment]
you're welcome!

**Comment by malopezcruz** [comment]
I ended up doing the following: 1) In Gemfile I added `gem 'ffi', '1 .9.3 '`. 2) After that I ran `bundle update ffi`. For now, it seems to be working.

**Comment by axyz** [comment]
yep, i've read that sometimes bundle update could solve these kind of problems, by the way having a clean ruby environment is always a good habit: it's easy that after some time playing with a big amount of gems and different ruby versions that things could become very messy...
