### ISSUE TITLE
small typo in readme

### ISSUE THREAD

**Issue by wanderingcrow** [axyz/middleman-zurb-foundation#5]
$ middleman init my_new_project --template=zurb-foundation should be: 
$ middleman init my_new_project --template=middleman-zurb-foundation I think.

**Comment by axyz** [comment]
Hi there, 
it is not a typo, it actually depends by the name of the directory in which you clone it: in the README i use this string:

git clone git://github.com/axyz/middleman-zurb-foundation.git ~/.middleman/zurb-foundation

so the template name will be zurb-foundation (I don't like to repeat middleman in all the templates, while it make sense for the github repo name, by the way you can clone it with whatever name you like and call the template accordingly)
